# -*- coding: utf-8 -*-
"""unify to American English.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vBMQyB8svOPNNOqtKoOJe08kq5CIQEN3
"""

import re

british_to_american = {
    # -our → -or
    "colour": "color",
    "colourful": "colorful",
    "watercolour": "watercolor",
    "favour": "favor",
    "honour": "honor",
    "labour": "labor",
    "neighbour": "neighbor",
    "rumour": "rumor",

    # -re → -er
    "centre": "center",
    "theatre": "theater",
    "metre": "meter",
    "litre": "liter",

    # -ise → -ize
    "organise": "organize",
    "realise": "realize",
    "recognise": "recognize",
    "apologise": "apologize",

    # double l
    "travelling": "traveling",
    "cancelled": "canceled",
    "modelling": "modeling",

    # misc spelling
    "grey": "gray",
    "cheque": "check",
    "programme": "program",
    "jewellery": "jewelry",
    "defence": "defense",
    "offence": "offense",
    "licence": "license",
    "tyre": "tire",
    "aluminium": "aluminum",
}


def unify_to_american(text, mapping):
    def replace(match):
        word = match.group(0)
        lower = word.lower()
        if lower in mapping:
            replacement = mapping[lower]
            return replacement.capitalize() if word[0].isupper() else replacement
        return word

    return re.sub(r"\b\w+\b", replace, text)

with open("catalog_data.txt", "r", encoding="utf-8") as f:
    text = f.read()

converted = unify_to_american(text, british_to_american)

with open("catalog_data_unified.txt", "w", encoding="utf-8") as f:
    f.write(converted)